options:
  locust_file:
    type: string
    default: ""
    description: "The locust_file to use, base64 encoded."
  master:
    type: boolean
    default: False
    description: "Whether to run in master mode."
  host:
    type: string
    default: ""
    description: "The host to run the load test on."
  pip_packages:
    type: string
    default: ""
    description: "A list of packages to install in the locust venv, in requiresments file format."
