- hosts: all
  vars:
    working_dir: /srv/locustio
  handlers:
    - name: Restart locust
      service: name=locustio state=restarted
  tasks:
    - name: Install required packages.
      apt: pkg={{ item }} state=latest update_cache=yes
      with_items:
        - python-pip
        - python-virtualenv
        - python-dev
        - gcc
        - g++
      tags:
        - install
        - upgrade-charm

    - name: Install pyzmq
      pip: name=pyzmq
           virtualenv={{ working_dir }}/env
      tags:
        - install
        - upgrade-charm

    - name: Install locustio
      pip: name=locustio
           virtualenv={{ working_dir }}/env
      tags:
        - install
        - upgrade-charm

    - name: Write locustfile
      template: src=../templates/locust_file.py
                dest={{ working_dir }}/locust_file.py
      tags:
        - config-changed
        - master-relation-changed
      when: master or master__private_address is defined
      notify:
        - Restart locust

    - name: Write service file
      template: src=../templates/locustio.init.conf
                dest=/etc/init/locustio.conf
      tags:
        - config-changed
        - master-relation-changed
      when: master or master__private_address is defined
      notify:
        - Restart locust

    - name: No-op task for hooks without any tasks tagged.
      tags:
        - start
        - stop
      debug: msg="No ansible tasks tagged."
